### ISSUE TITLE
Endless appearance of "update popup" with SDK 4.5.0 (using new API "setCheckForUpdatesBackground")

### ISSUE THREAD

**Issue by woa1mu** [applivery/applivery-ios-sdk#96]
**Describe the bug**
After updating to SDK `4.5.0` and integration of `setCheckForUpdatesBackground`, the SDK keeps showing the "update popup".

**To Reproduce**
1. Integrate SDK `4.5.0` (https://github.com/applivery/applivery-ios-sdk/releases/tag/4.5.0)
2. Start using `setCheckForUpdatesBackground` when setting up `AppliverySDK`. 
3. Install the App, which contains SDK `4.5.0`(it is the most recent version of the App, no newer update exists)
4. After the installation, launch the App
 
**Expected behavior**
Since it is the most recent version of the App and no newer version exists in Applivery, there should not appear a "update popup".

**Actual behavior**
We can see "update popup" when launching the App after installation in an endless loop.
"update popup" -> installation -> launch -> "update popup"....
The current installed version of our App is the most recent version available in Applivery and no newer version exists. And yet the "update popup" appears repeatedly.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPhone 16 Pro
 - OS: iOS 16.0.1
 - Browser: Firefox 143.2 (62218)

**Additional context**
* https://github.com/applivery/applivery-ios-sdk/pull/84
* https://github.com/applivery/applivery-ios-sdk/issues/76

**Comment by abbydomi** [comment]
Hello! Should be solved in 4.5.1 https://github.com/applivery/applivery-ios-sdk/releases/tag/4.5.1

**Comment by woa1mu** [comment]
Hello @abbydomi , unfortunately I still see the "update popup" everytime I launch the App.
This is even reproducible after a fresh installation (uninstall before) of the most recent version of the App.

**Comment by woa1mu** [comment]
@abbydomi What does 
```func checkOtaUpdate(_ config: SDKData?, version: String) -> Bool {```
expect as **version**?

Does it expect an app-version (CFBundleShortVersionString) or the build-number (CFBundleVersion).
In [UpdateService.swift#L207](https://github.com/applivery/applivery-ios-sdk/blob/master/AppliverySDK/Services/UpdateService.swift#L207) *checkOtaUpdate* is execute with **appVersion**
```
checkOtaUpdate(updateConfig.config, version: appVersion)
```
 (<--- I believe here we should use **updateConfig.buildNumber** instead)

but in [UpdateService.swift#L291](https://github.com/applivery/applivery-ios-sdk/blob/master/AppliverySDK/Services/UpdateService.swift#L291) it is executed with **config.buildNumber**
```
checkOtaUpdate(config.config, version: config.buildNumber)
```

I think we simply need to change [UpdateService.swift#L207](https://github.com/applivery/applivery-ios-sdk/blob/master/AppliverySDK/Services/UpdateService.swift#L207) to:
```
if checkOtaUpdate(updateConfig.config, version: updateConfig.buildNumber)
```

**Comment by abbydomi** [comment]
Thanks for the observation, checkOtaUpdate was indeed checking the wrong version, I've uploaded a new fix (https://github.com/applivery/applivery-ios-sdk/pull/100), version 4.5.2 will follow shortly

**Comment by woa1mu** [comment]
@abbydomi I can confirm that **[4.5.2](https://github.com/applivery/applivery-ios-sdk/releases/tag/4.5.2)** solves this issue - thanks for the fix 😄
